# Generated by Django 4.2.13 on 2026-04-06 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_booking_options_person_groups_person_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='driver',
            field=models.ForeignKey(blank=True, db_column='driver_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
