# Generated by Django 4.2.13 on 2026-04-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vehicle_driver_lat_vehicle_driver_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Vehicle Photo'),
        ),
    ]
