# Generated by Django 5.2.13 on 2026-05-03 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_vehicle_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('micro_truck', 'Micro Truck'), ('mini_truck', 'Mini Truck'), ('pickup_truck', 'Pickup Truck'), ('light_truck', 'Light Truck'), ('medium_truck', 'Medium Truck'), ('heavy_truck', 'Heavy Truck'), ('trailer', 'Trailer'), ('flatbed', 'Flatbed'), ('dumper', 'Dumper'), ('jcb', 'JCB'), ('excavator', 'Excavator'), ('tractor', 'Tractor')], max_length=50)),
                ('subtype', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='driver_vehicles/')),
                ('number_plate', models.CharField(max_length=20, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('price_per_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(db_column='driver_id', limit_choices_to={'role': 'Driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicles', to=settings.AUTH_USER_MODEL)),
                ('linked_vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_vehicle_source', to='myapp.vehicle')),
            ],
            options={
                'db_table': 'driver_vehicle',
                'ordering': ['-created_at'],
            },
        ),
    ]
